# Generated by Django 4.1.2 on 2022-11-07 06:36

from django.db import migrations, models
import django.db.models.deletion
import pharmacies.models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('document', models.FileField(upload_to=pharmacies.models._upload_path, verbose_name='Document')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacies.manager', verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Processing', 'В обработке'), ('Processed', 'Обработан'), ('Canceled', 'Отменён')], max_length=13)),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacies.document', verbose_name='Document')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacies.manager', verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-created',),
            },
        ),
    ]
